# Site settings
<<<<<<< HEAD
title: Menu Translate | AI Menu Translation & Ordering.
description: "Snap a menu photo for instant AI translation in 9 languages. Get cultural context, pronunciation help, and visual order sheets. Never guess what you're ordering again!"
url: "https://5amfung.github.io/menu-translate-website"
author:
  name: "Menu Translate"
  url: "https://5amfung.github.io/menu-translate-website"
=======
title: Monochrome | A minimal, responsive Jekyll blog theme
description: "A minimal, responsive, ready to use blog template, built with Jekyll."
url: "http://www.dyutibarma.github.io/monochrome"
author:
  name: "The Review Index"
  email: "dyutibarma@gmail.com"
  url: "https://thereviewindex.com"
>>>>>>> b364e6988a5819999f5217d55a9001dcd8c3c9f9

# Build settings
baseurl: /menu-translate-website # Change this to your relative path (ex: /blog/), or leave just a /
markdown: kramdown
source: .
destination: ./_site
permalink: /:title
paginate: 8
paginate_path: /page:num/

# Default values
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

# Plugins
gems:
  - jekyll-paginate
  - jekyll-sitemap

# Custom variables
version: "1.0.0"

# Options
<<<<<<< HEAD
=======
custom_header: false
>>>>>>> b364e6988a5819999f5217d55a9001dcd8c3c9f9
custom_nav_footer: false
reverse: false
